import { type Candidate } from "./types.d"

const objects: Candidate[] = [
    { name: "chidiya", spoken: "चिड़िया", canFly: true },
    { name: "kauwa", spoken: "कौवा", canFly: true },
    { name: "kabootar", spoken: "कबूतर", canFly: true },
    { name: "tota", spoken: "तोता", canFly: true },
    { name: "mor", spoken: "मोर", canFly: true },
    { name: "murgi", spoken: "मुर्गी", canFly: true },
    { name: "batakh", spoken: "बत्तख", canFly: true },
    { name: "hans", spoken: "हंस", canFly: true },
    { name: "baaz", spoken: "बाज़", canFly: true },
    { name: "cheel", spoken: "चील", canFly: true },
    { name: "ullu", spoken: "उल्लू", canFly: true },
    { name: "maina", spoken: "मैना", canFly: true },
    { name: "bulbul", spoken: "बुलबुल", canFly: true },
    { name: "koel", spoken: "कोयल", canFly: true },
    { name: "flamingo", spoken: "फ्लेमिंगो", canFly: true },
    { name: "penguin", spoken: "पेंगुइन", canFly: false },
    { name: "ostrich", spoken: "ऑस्ट्रिच", canFly: false },
    { name: "emu", spoken: "ईमू", canFly: false },
    { name: "kiwi", spoken: "कीवी", canFly: false },
    { name: "murga", spoken: "मुर्गा", canFly: false },

    { name: "chamgadad", spoken: "चमगादड़", canFly: true },
    { name: "titli", spoken: "तितली", canFly: true },
    { name: "madhumakkhi", spoken: "मधुमक्खी", canFly: true },
    { name: "machhar", spoken: "मच्छर", canFly: true },
    { name: "makhi", spoken: "मक्खी", canFly: true },
    { name: "dragonfly", spoken: "ड्रैगनफ्लाई", canFly: true },
    { name: "tiddi", spoken: "टिड्डी", canFly: true },
    { name: "patanga", spoken: "पतंगा", canFly: true },
    { name: "ladybug", spoken: "लेडीबग", canFly: true },
    { name: "cockroach", spoken: "कॉकरोच", canFly: true },

    { name: "haathi", spoken: "हाथी", canFly: false },
    { name: "sher", spoken: "शेर", canFly: false },
    { name: "bagh", spoken: "बाघ", canFly: false },
    { name: "cheetah", spoken: "चीता", canFly: false },
    { name: "ghoda", spoken: "घोड़ा", canFly: false },
    { name: "gadha", spoken: "गधा", canFly: false },
    { name: "gaay", spoken: "गाय", canFly: false },
    { name: "bhains", spoken: "भैंस", canFly: false },
    { name: "bakri", spoken: "बकरी", canFly: false },
    { name: "bhed", spoken: "भेड़", canFly: false },
    { name: "kutta", spoken: "कुत्ता", canFly: false },
    { name: "billi", spoken: "बिल्ली", canFly: false },
    { name: "khargosh", spoken: "खरगोश", canFly: false },
    { name: "bandar", spoken: "बंदर", canFly: false },
    { name: "gorilla", spoken: "गोरिल्ला", canFly: false },
    { name: "jiraaf", spoken: "जिराफ़", canFly: false },
    { name: "zebra", spoken: "ज़ेब्रा", canFly: false },
    { name: "oont", spoken: "ऊँट", canFly: false },
    { name: "suar", spoken: "सूअर", canFly: false },
    { name: "hiran", spoken: "हिरण", canFly: false },

    { name: "magarmach", spoken: "मगरमच्छ", canFly: false },
    { name: "kachhua", spoken: "कछुआ", canFly: false },
    { name: "saap", spoken: "साँप", canFly: false },
    { name: "chipkali", spoken: "छिपकली", canFly: false },
    { name: "mendhak", spoken: "मेंढक", canFly: false },
    { name: "machhli", spoken: "मछली", canFly: false },
    { name: "shark", spoken: "शार्क", canFly: false },
    { name: "whale", spoken: "व्हेल", canFly: false },
    { name: "octopus", spoken: "ऑक्टोपस", canFly: false },
    { name: "crab", spoken: "क्रैब", canFly: false },

    { name: "hawai jahaj", spoken: "हवाई जहाज़", canFly: true },
    { name: "helicopter", spoken: "हेलिकॉप्टर", canFly: true },
    { name: "rocket", spoken: "रॉकेट", canFly: true },
    { name: "drone", spoken: "ड्रोन", canFly: true },
    { name: "hot air balloon", spoken: "हॉट एयर बैलून", canFly: true },
    { name: "kite", spoken: "काइट", canFly: true },
    { name: "paper plane", spoken: "पेपर प्लेन", canFly: true },
    { name: "ufo", spoken: "यूएफ़ओ", canFly: true },
    { name: "paraglider", spoken: "पैराग्लाइडर", canFly: true },
    { name: "glider", spoken: "ग्लाइडर", canFly: true },

    { name: "car", spoken: "कार", canFly: false },
    { name: "bus", spoken: "बस", canFly: false },
    { name: "cycle", spoken: "साइकिल", canFly: false },
    { name: "bike", spoken: "बाइक", canFly: false },
    { name: "train", spoken: "ट्रेन", canFly: false },
    { name: "boat", spoken: "बोट", canFly: false },
    { name: "ship", spoken: "शिप", canFly: false },
    { name: "tractor", spoken: "ट्रैक्टर", canFly: false },
    { name: "truck", spoken: "ट्रक", canFly: false },
    { name: "auto", spoken: "ऑटो", canFly: false },

    { name: "pankha", spoken: "पंखा", canFly: false },
    { name: "kursi", spoken: "कुर्सी", canFly: false },
    { name: "mez", spoken: "मेज़", canFly: false },
    { name: "mobile", spoken: "मोबाइल", canFly: false },
    { name: "laptop", spoken: "लैपटॉप", canFly: false },
    { name: "ball", spoken: "बॉल", canFly: false },
    { name: "patthar", spoken: "पत्थर", canFly: false },
    { name: "seb", spoken: "सेब", canFly: false },
    { name: "kela", spoken: "केला", canFly: false },
    { name: "aam", spoken: "आम", canFly: false },

    { name: "superman", spoken: "सुपरमैन", canFly: true },
    { name: "iron man", spoken: "आयरन मैन", canFly: true },
    { name: "thor", spoken: "थॉर", canFly: true },
    { name: "spider-man", spoken: "स्पाइडर-मैन", canFly: false },
    { name: "batman", spoken: "बैटमैन", canFly: false },
    { name: "harry potter", spoken: "हैरी पॉटर", canFly: true },
    { name: "genie", spoken: "जीनी", canFly: true },
    { name: "pari", spoken: "परी", canFly: true },
    { name: "dragon", spoken: "ड्रैगन", canFly: true },
    { name: "unicorn", spoken: "यूनिकॉर्न", canFly: false },

    { name: "eagle", spoken: "ईगल", canFly: true },
    { name: "sparrow", spoken: "स्पैरो", canFly: true },
    { name: "crow", spoken: "क्रो", canFly: true },
    { name: "seagull", spoken: "सीगल", canFly: true },
    { name: "woodpecker", spoken: "वुडपेकर", canFly: true },
    { name: "kingfisher", spoken: "किंगफिशर", canFly: true },
    { name: "parakeet", spoken: "पैराकीट", canFly: true },
    { name: "vulture", spoken: "वल्चर", canFly: true },
    { name: "crane", spoken: "क्रेन", canFly: true },
    { name: "stork", spoken: "स्टॉर्क", canFly: true },
    { name: "pelican", spoken: "पेलिकन", canFly: true },
    { name: "heron", spoken: "हेरॉन", canFly: true },
    { name: "robin", spoken: "रॉबिन", canFly: true },
    { name: "canary", spoken: "कनैरी", canFly: true },
    { name: "falcon", spoken: "फाल्कन", canFly: true },
    { name: "hawk", spoken: "हॉक", canFly: true },
    { name: "swift", spoken: "स्विफ्ट", canFly: true },
    { name: "swallow", spoken: "स्वॉलो", canFly: true },
    { name: "hummingbird", spoken: "हमिंगबर्ड", canFly: true },
    { name: "macaw", spoken: "मकॉ", canFly: true },

    { name: "ant", spoken: "ऐंट", canFly: false },
    { name: "spider", spoken: "स्पाइडर", canFly: false },
    { name: "scorpion", spoken: "स्कॉर्पियन", canFly: false },
    { name: "snail", spoken: "स्नेल", canFly: false },
    { name: "earthworm", spoken: "अर्थवर्म", canFly: false },
    { name: "centipede", spoken: "सेंटीपीड", canFly: false },
    { name: "millipede", spoken: "मिलीपीड", canFly: false },
    { name: "beetle", spoken: "बीटल", canFly: true },
    { name: "wasp", spoken: "वॉस्प", canFly: true },
    { name: "firefly", spoken: "फायरफ्लाई", canFly: true },

    { name: "rhino", spoken: "राइनो", canFly: false },
    { name: "hippo", spoken: "हिप्पो", canFly: false },
    { name: "wolf", spoken: "वुल्फ", canFly: false },
    { name: "fox", spoken: "फॉक्स", canFly: false },
    { name: "jackal", spoken: "जैकल", canFly: false },
    { name: "hyena", spoken: "हाइना", canFly: false },
    { name: "bear", spoken: "बेयर", canFly: false },
    { name: "panda", spoken: "पांडा", canFly: false },
    { name: "koala", spoken: "कोआला", canFly: false },
    { name: "kangaroo", spoken: "कंगारू", canFly: false },
    { name: "lemur", spoken: "लीमर", canFly: false },
    { name: "otter", spoken: "ऑटर", canFly: false },
    { name: "beaver", spoken: "बीवर", canFly: false },
    { name: "porcupine", spoken: "पॉर्क्यूपाइन", canFly: false },
    { name: "hedgehog", spoken: "हेजहॉग", canFly: false },
    { name: "camel", spoken: "कैमल", canFly: false },
    { name: "donkey", spoken: "डॉन्की", canFly: false },
    { name: "yak", spoken: "याक", canFly: false },
    { name: "buffalo", spoken: "बफैलो", canFly: false },
    { name: "deer", spoken: "डियर", canFly: false },

    { name: "dolphin", spoken: "डॉल्फिन", canFly: false },
    { name: "seal", spoken: "सील", canFly: false },
    { name: "walrus", spoken: "वॉलरस", canFly: false },
    { name: "starfish", spoken: "स्टारफिश", canFly: false },
    { name: "jellyfish", spoken: "जेलीफिश", canFly: false },
    { name: "lobster", spoken: "लॉब्स्टर", canFly: false },
    { name: "shrimp", spoken: "श्रिम्प", canFly: false },
    { name: "eel", spoken: "ईल", canFly: false },
    { name: "stingray", spoken: "स्टिंगरे", canFly: false },
    { name: "seahorse", spoken: "सीहॉर्स", canFly: false },

    { name: "zeppelin", spoken: "ज़ेपलिन", canFly: true },
    { name: "airship", spoken: "एयरशिप", canFly: true },
    { name: "fighter jet", spoken: "फाइटर जेट", canFly: true },
    { name: "space shuttle", spoken: "स्पेस शटल", canFly: true },
    { name: "satellite", spoken: "सैटेलाइट", canFly: true },

    { name: "submarine", spoken: "सबमरीन", canFly: false },
    { name: "canoe", spoken: "कैनो", canFly: false },
    { name: "kayak", spoken: "कयाक", canFly: false },
    { name: "scooter", spoken: "स्कूटर", canFly: false },
    { name: "skateboard", spoken: "स्केटबोर्ड", canFly: false },

    { name: "frisbee", spoken: "फ्रिस्बी", canFly: true },
    { name: "balloon", spoken: "बैलून", canFly: true },
    { name: "soap bubble", spoken: "सोप बबल", canFly: true },
    { name: "leaf", spoken: "लीफ", canFly: true },
    { name: "feather", spoken: "फेदर", canFly: true },
    { name: "newspaper", spoken: "न्यूज़पेपर", canFly: true },
    { name: "plastic bag", spoken: "प्लास्टिक बैग", canFly: true },
    { name: "parachute", spoken: "पैराशूट", canFly: true },
    { name: "confetti", spoken: "कन्फेटी", canFly: true },
    { name: "dust", spoken: "डस्ट", canFly: true },

    { name: "table", spoken: "टेबल", canFly: false },
    { name: "sofa", spoken: "सोफ़ा", canFly: false },
    { name: "television", spoken: "टेलीविज़न", canFly: false },
    { name: "refrigerator", spoken: "रेफ्रिजरेटर", canFly: false },
    { name: "washing machine", spoken: "वॉशिंग मशीन", canFly: false },
    { name: "microwave", spoken: "माइक्रोवेव", canFly: false },
    { name: "book", spoken: "बुक", canFly: false },
    { name: "pencil", spoken: "पेंसिल", canFly: false },
    { name: "bottle", spoken: "बॉटल", canFly: false },
    { name: "umbrella", spoken: "अम्ब्रेला", canFly: false },

    { name: "witch", spoken: "विच", canFly: true },
    { name: "ghost", spoken: "घोस्ट", canFly: true },
    { name: "angel", spoken: "एंजेल", canFly: true },
    { name: "phoenix", spoken: "फीनिक्स", canFly: true },
    { name: "pegasus", spoken: "पेगासस", canFly: true },
    { name: "fairy", spoken: "फेयरी", canFly: true },
    { name: "demon", spoken: "डीमन", canFly: true },
    { name: "rocket raccoon", spoken: "रॉकेट रैकून", canFly: false },
    { name: "hulk", spoken: "हल्क", canFly: false },
    { name: "captain america", spoken: "कैप्टन अमेरिका", canFly: false },
];

export default objects
